{
 "title": "SLO/SLI - Voting API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidade /votes (SLI) - meta 99%",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{path=\"/votes\", status!~\"5..\"}[5m])) / sum(rate(http_requests_total{path=\"/votes\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latência p95 /votes agora",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=\"/votes\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Taxa de erro por rota (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[5m])) by (path, status)",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Latência p95 /votes (SLI) - meta < 250ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=\"/votes\"}[5m])) by (le))",
     "legendFormat": "p95 latency"
    }
   ]
  },
  {
   "title": "Requisições por segundo (todas as rotas)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}